server:
  port: 10011
spring:
  application:
    name: resource-server

security:
  oauth2:
    client:
      client-id: admin
      client-secret: 112233
      user-authorization-uri: http://localhost:10010/oauth/authorize
      access-token-uri: http://localhost:10010/oauth/token
    resource:
      token-info-uri: http://localhost:10010/oauth/check_token